// #GENERIC
exports.APPLICATION_NAME = 'snce-nextjs'

// #REVALIDATE TIME (s)
exports.REVALIDATE_TIME_PREPROD = 1
exports.REVALIDATE_TIME_PROD = 3600

// #CONTENFUL API SETTINGS
exports.LINK_LEVEL = 10